Fixes and more features
HorseNuggets/TerminatorPlus pull request #68
Opened 2024-09-22 17:46 UTC by ThisTestUser

Full list of features:
- Added customlist targeting mode
- Added /botenv for creating custom list of targets
- Added support in /botenv for modded Magma servers (irrelevant for this version)
- Fixed target option PLAYER
- Fixed autofill bugs and add aliases in autofill
- Fixed bot not appearing in tablist when addplayerlist enabled
- Fixed held items sometimes not updating (for example totems)
- Sound retrieval fixes
- Better tool switching (cosmetic)
- Extra /bot debug commands and autofill

2024-09-22 17:48 UTC, Badbird5907 commented
:eyes: I'll have a look at this PR in a bit (a couple of hours), please ping me on discord tonight if I forget.

2024-09-25 02:07 UTC, Badbird5907 requested changes
LGTM

2024-09-25 02:07 UTC, Badbird5907 commented on TerminatorPlus-Plugin/src/main/java/net/nuggetmc/tplus/bot/Bot.java
> +        // Magma fix - In case a mod causes the Bukkit entity to be created too early
I personally don't like supporting hybrid servers, but sure.

2024-09-25 02:07 UTC, Badbird5907 commented on TerminatorPlus-Plugin/src/main/java/net/nuggetmc/tplus/command/commands/BotEnvironmentCommand.java
> +    private static Set<String> getLoadedMods() {
Hybrid support

2024-09-25 02:20 UTC, Badbird5907 commented
On second thought, could you please move the hybrid server support to a fork of this repo?
I won't be maintaining nor testing the support for hybrid servers, and I think it would be easier to maintain your own fork with those features and pull in patches from upstream.

2024-09-26 00:44 UTC, ThisTestUser commented
All code referencing hybrid server classes have been removed. I've kept /botenv addSolid as that only uses Bukkit/Vanilla methods.

2024-09-27 00:24 UTC, Badbird5907 approved these changes
LGTM!

Thank You!

2024-09-27 00:24 UTC, merged